INSERT INTO `pool_quest` VALUES (25155, 523, 'Misiones joyeria alianza');
INSERT INTO `pool_quest` VALUES (25154, 523, 'Misiones joyeria alianza');
INSERT INTO `pool_quest` VALUES (25157, 523, 'Misiones joyeria alianza');
INSERT INTO `pool_quest` VALUES (25105, 523, 'Misiones joyeria alianza');
INSERT INTO `pool_quest` VALUES (25161, 524, 'Misiones joyeria horda');
INSERT INTO `pool_quest` VALUES (25160, 524, 'Misiones joyeria horda');
INSERT INTO `pool_quest` VALUES (25159, 524, 'Misiones joyeria horda');
INSERT INTO `pool_quest` VALUES (25158, 524, 'Misiones joyeria horda');
INSERT INTO `pool_quest` VALUES (26190, 530, 'Misiones Cocina ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26183, 530, 'Misiones Cocina ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26153, 530, 'Misiones Cocina ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26192, 530, 'Misiones Cocina ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26177, 530, 'Misiones Cocina ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26227, 531, 'Misiones Cocina Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26235, 531, 'Misiones Cocina Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26226, 531, 'Misiones Cocina Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26233, 531, 'Misiones Cocina Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26220, 531, 'Misiones Cocina Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26414, 532, 'Misiones Pesca ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26442, 532, 'Misiones Pesca ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26536, 532, 'Misiones Pesca ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26420, 532, 'Misiones Pesca ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26488, 532, 'Misiones Pesca ventormenta alianza');
INSERT INTO `pool_quest` VALUES (26543, 533, 'Misiones Pesca Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26557, 533, 'Misiones Pesca Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26572, 533, 'Misiones Pesca Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26556, 533, 'Misiones Pesca Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (26588, 533, 'Misiones Pesca Orgrimmar horda');
INSERT INTO `pool_quest` VALUES (11370, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11373, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11362, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11368, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11388, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11386, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11382, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11363, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11499, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11375, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11354, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11378, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11374, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11372, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11384, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (11369, 534, 'Misiones Comerciante de viento Zhareem');
INSERT INTO `pool_quest` VALUES (14074, 34880, 'Tournament - Champion - The Silver Covenant - Sea - A Leg Up');
INSERT INTO `pool_quest` VALUES (14152, 34880, 'Tournament - Champion - The Silver Covenant - Sea - Rescue At Sea');
INSERT INTO `pool_quest` VALUES (14077, 34880, 'Tournament - Champion - The Silver Covenant - Sea - The Lights Mercy');
INSERT INTO `pool_quest` VALUES (14080, 34880, 'Tournament - Champion - The Silver Covenant - Sea - Stop the Aggression');
INSERT INTO `pool_quest` VALUES (14143, 34771, 'Tournament - Champion - The Sunreavers - Sea - A Leg Up');
INSERT INTO `pool_quest` VALUES (14136, 34771, 'Tournament - Champion - The Sunreavers - Sea - Rescue At Sea');
INSERT INTO `pool_quest` VALUES (14144, 34771, 'Tournament - Champion - The Sunreavers - Sea - The Lights Mercy');
INSERT INTO `pool_quest` VALUES (14140, 34771, 'Tournament - Champion - The Sunreavers - Sea - Stop the Aggression');
INSERT INTO `pool_quest` VALUES (14092, 34912, 'Tournament - Champion - The Silver Covenant - Tournament - Breakfast Of Champions');
INSERT INTO `pool_quest` VALUES (14141, 34912, 'Tournament - Champion - The Silver Covenant - Tournament - Gormok Wants His Snobolds');
INSERT INTO `pool_quest` VALUES (14145, 34912, 'Tournament - Champion - The Silver Covenant - Tournament - What Do You Feed a Yeti, Anyway?');
INSERT INTO `pool_quest` VALUES (14076, 34914, 'Tournament - Champion - The Sunreavers - Tournament - Breakfast Of Champions');
INSERT INTO `pool_quest` VALUES (14090, 34914, 'Tournament - Champion - The Sunreavers - Tournament - Gormok Wants His Snobolds');
INSERT INTO `pool_quest` VALUES (14112, 34914, 'Tournament - Champion - The Sunreavers - Tournament - What Do You Feed a Yeti, Anyway?');
INSERT INTO `pool_quest` VALUES (14101, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Drottinn Hrothgar');
INSERT INTO `pool_quest` VALUES (14102, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Mistcaller Yngvar');
INSERT INTO `pool_quest` VALUES (14104, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Ornolf The Scarred');
INSERT INTO `pool_quest` VALUES (14105, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Deathspeaker Kharos');
INSERT INTO `pool_quest` VALUES (14107, 35094, 'Tournament - Champion - The Argent Crusade - Kraken - The Fate Of The Fallen');
INSERT INTO `pool_quest` VALUES (14108, 35094, 'Tournament - Champion - The Argent Crusade - Kraken - Get Kraken!');
